<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/IntProg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# phase 1 (2 rules!!)
# write standardizing:) in a function if you could!!!
# And that's it:)


# IntProg

In [2]:
from scipy.optimize import LinearConstraint, milp
import numpy as np

In [ ]:
c = np.array([3, 4])
A = np.array([[-3, -1], [-1, -2]])
b_u = np.array([-4, -4])
b_l = np.full_like(b_u, -np.inf, dtype=float)
# b_l = np.full_like(b_u, 0, dtype=float)

In [ ]:
constraints = LinearConstraint(A, b_l, b_u)

In [ ]:
integrality = np.ones_like(c)
res = milp(c=c, constraints=constraints, integrality=integrality)
res.x

array([2., 1.])

In [ ]:
res = milp(c=c, constraints=constraints)  # OR:
# from scipy.optimize import linprog; res = linprog(c, A, b_u)
res.x

array([0.8, 1.6])

# Linprog

In [ ]:
from scipy.optimize import linprog
c = [3, 4]
A = [[-3, -1], [-1, -2]]
b = [-4, -4]
x0_bounds = (0, None)
x1_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds])
res.fun


8.8

In [ ]:
res.x

array([0.8, 1.6])

In [ ]:
res.message

'Optimization terminated successfully. (HiGHS Status 7: Optimal)'

# The Algorithm

In [ ]:
def Phase1(tableau):
    basics = tableau[1:,0].copy() # start drom zero as the first element!!
    m, n = tableau.shape
    m -=1
    n -=2
    while True:
        # Check if we have an optimal solution (all entries in the objective row are negative)
        if np.all(tableau[0, 1:-1] <= 0):
            break
        # Pivot column (most negative entry in the objective row)
        pivot_col = np.argmax(tableau[0, 1:-1])+1
        # Pivot row
        ratios = np.divide(tableau[1:, -1], tableau[1:, pivot_col])
        # print(ratios)
        valid_ratios = ratios[tableau[1:, pivot_col] > 0]
        # print(valid_ratios)
        # Check if there's no valid ratio which means unbounded
        if len(valid_ratios) == 0:
            raise ValueError("The problem is unbounded.")
        ########could be written better################
        pivot_row = np.where(ratios == valid_ratios.min())[0][0] +1
        # Pivot element
        pivot_element = tableau[pivot_row, pivot_col]
        # Update the pivot row
        tableau[pivot_row] /= pivot_element
        # Update the other rows
        for i in range(m + 1):
            if i != pivot_row:
                # print(i)
                tableau[i] -= tableau[i, pivot_col] * tableau[pivot_row]

        basics[pivot_row-1] = pivot_col-1
    tableau[1:, 0] = basics
    tableau[0, 0] = 1
    return tableau


In [54]:
def CoreSimplex(tableau):
    basics = tableau[1:,0].copy() # start drom zero as the first element!!
    m, n = tableau.shape
    m -=1
    n -=2
    while True:
        # Check if we have an optimal solution (all entries in the objective row are negative)
        if np.all(tableau[0, 1:-1] <= 0):
            break
        # Pivot column (most negative entry in the objective row)
        pivot_col = np.argmax(tableau[0, 1:-1])+1
        # Pivot row
        ratios = np.divide(tableau[1:, -1], tableau[1:, pivot_col])
        # print(ratios)
        valid_ratios = ratios[tableau[1:, pivot_col] > 0]
        # print(valid_ratios)
        # Check if there's no valid ratio which means unbounded
        if len(valid_ratios) == 0:
            raise ValueError("The problem is unbounded.")
        ########could be written better################
        pivot_row = np.where(ratios == valid_ratios.min())[0][0] +1
        # Pivot element
        pivot_element = tableau[pivot_row, pivot_col]
        # Update the pivot row
        tableau[pivot_row] /= pivot_element
        # Update the other rows
        for i in range(m + 1):
            if i != pivot_row:
                # print(i)
                tableau[i] -= tableau[i, pivot_col] * tableau[pivot_row]

        basics[pivot_row-1] = pivot_col-1
    tableau[1:, 0] = basics
    tableau[0, 0] = 1
    return tableau


In [56]:
t = np.array(
    [[ 1, -1,  4,  0,  0,  0,  0],
     [ 2, -1,  1,  1,  0,  0,  1],
     [ 3, -1,  4,  0,  1,  0,  7],
     [ 4,  3,  1,  0,  0,1.0, 18]])
print(np.round(CoreSimplex(t), 4))

[[ 1.      0.      0.      0.     -1.      0.     -7.    ]
 [ 1.      0.      1.     -0.3333  0.3333  0.      2.    ]
 [ 0.      1.      0.     -1.3333  0.3333  0.      1.    ]
 [ 4.      0.      0.      4.3333 -1.3333  1.     13.    ]]


In [ ]:

# needs to checked if variables are all positive
def simplex(c, A, b):
    # Number of variables
    n = len(c)
    # Number of constraints
    m = len(b)
    # creation of bfs(Basic feasible solution through Artificial variables)
    Rtableau = np.zeros((m + 1, n + m + 1))
    Rtableau[1:, :n] = A
    Rtableau[1:, -1] = b
    p = np.eye(m+1)
    p[np.where(b<0)+np.ones_like(np.where(b<0))] *= -1
    Rtableau = p @ Rtableau
    Rtableau[1:, n:n+m] = np.eye(m)
    #
    Rtableau[0, n:n+m] = -np.ones(m)
    # Standardizing:)
    for i in range(m):
        Rtableau[0] += Rtableau[i+1]


    Rtableau = CoreSimplex(Rtableau)
    # checking the feasibility
    # if
    tableau = np.delete(Rtableau, np.s_[n:n+m], axis=1)


    tableau[0, :-1] = -c
    # Standardizing :)
    for i in range(m):
        # print(i)
        # print((tableau[0, np.where(tableau[i+1]==1)[0]]))
        tableau[0] -= tableau[0, np.where(tableau[i+1]==1)[0]] * tableau[i+1]
    # print(tableau)
    tableau = CoreSimplex(tableau)


    return tableau


In [ ]:
A = np.array([
    [3, 1,-1, 0],
    [1, 2, 0,-1],

])
b = np.array([4, 4])
c = np.array([3, 4, 0, 0])
np.round(simplex(c, A, b),4)

array([[ 0. ,  0. , -0.4, -1.8,  8.8],
       [ 1. ,  0. , -0.4,  0.2,  0.8],
       [ 0. ,  1. ,  0.2, -0.6,  1.6]])

In [ ]:
# needs to checked if variables are all positive
def intSimplex(c, A, b):
    # Number of variables
    n = len(c)
    # Number of constraints
    m = len(b)
    # creation of bfs(Basic feasible solution through Artificial variables)
    Rtableau = np.zeros((m + 1, n + m + 1))
    Rtableau[1:, :n] = A
    Rtableau[1:, -1] = b
    p = np.eye(m+1)
    p[np.where(b<0)+np.ones_like(np.where(b<0))] *= -1
    Rtableau = p @ Rtableau
    Rtableau[1:, n:n+m] = np.eye(m)
    #
    Rtableau[0, n:n+m] = -np.ones(m)
    for i in range(m):
        Rtableau[0] += Rtableau[i+1]


    Rtableau = CoreSimplex(Rtableau)
    # checking the feasibility
    # if
    tableau = np.delete(Rtableau, np.s_[n:n+m], axis=1)


    tableau[0, :-1] = -c
    for i in range(m):
        # print(i)
        # print((tableau[0, np.where(tableau[i+1]==1)[0]]))
        tableau[0] -= tableau[0, np.where(tableau[i+1]==1)[0]] * tableau[i+1]
    # print(tableau)
    tableau = CoreSimplex(tableau)

    while True:
        # Check if we have an optimal solution (all entries in the objective row are negative)
        if np.all(np.modf(tableau[1:, -1])[0] == 0):
            break
        ########could be written better################
        # fracIdx = (np.where(np.modf(tableau[1:, -1])[0] != 0)[0]+1)[0]
        fracIdx = 2
        # print(tableau[fracIdx]-np.floor(tableau[fracIdx]))
        tableau = np.vstack((tableau, -(tableau[fracIdx]-np.floor(tableau[fracIdx]))))
        newVar = np.zeros(tableau.shape[0])
        newVar[-1] = 1
        tableau = np.insert(tableau, -1, newVar, axis=1)

        # tableau = simplex(tableau[0, :-1], tableau[1:, :-1], tableau[1:, -1])

        print(tableau)
        print(tableau[0, :-1])
        print( tableau[1:, :-1])
        print( tableau[1:, -1])

        break
    return tableau


In [ ]:
A = np.array([
    [3, 1,-1, 0],
    [1, 2, 0,-1],

])
b = np.array([4, 4])
c = np.array([3, 4, 0, 0])
np.round(intSimplex(c, A, b),4)

[[ 0.   0.  -0.4 -1.8  0.   8.8]
 [ 1.   0.  -0.4  0.2  0.   0.8]
 [ 0.   1.   0.2 -0.6  0.   1.6]
 [-0.  -0.  -0.2 -0.4  1.  -0.6]]
[ 0.   0.  -0.4 -1.8  0. ]
[[ 1.   0.  -0.4  0.2  0. ]
 [ 0.   1.   0.2 -0.6  0. ]
 [-0.  -0.  -0.2 -0.4  1. ]]
[ 0.8  1.6 -0.6]


array([[ 0. ,  0. , -0.4, -1.8,  0. ,  8.8],
       [ 1. ,  0. , -0.4,  0.2,  0. ,  0.8],
       [ 0. ,  1. ,  0.2, -0.6,  0. ,  1.6],
       [-0. , -0. , -0.2, -0.4,  1. , -0.6]])

In [ ]:
import numpy as np

# Example 5x7 array
S = np.random.rand(3, 4)

# New column to insert
new_column = np.zeros(3)

# Print the original array
print("Original array:\n", S)

# Insert the new column at the 5th position (index 4)
S_modified = np.insert(S, -2, new_column, axis=1)

# Print the modified array
print("Modified array (with new column at 5th position):\n", S_modified)


Original array:
 [[0.28111349 0.03762787 0.0363364  0.88503735]
 [0.69939991 0.99581945 0.79337558 0.5424922 ]
 [0.10078401 0.73194852 0.64699449 0.25804583]]
Modified array (with new column at 5th position):
 [[0.28111349 0.03762787 0.         0.0363364  0.88503735]
 [0.69939991 0.99581945 0.         0.79337558 0.5424922 ]
 [0.10078401 0.73194852 0.         0.64699449 0.25804583]]


In [ ]:
import numpy as np

# Example array
arr = np.array([-2.5, 2.5, 3.0, 4.2, -3.7])

# Get the integral part using floor
integral_part = np.floor(arr)

# Get the fractional part by subtracting the integral part from the original array
fractional_part = arr - integral_part

print("Array:", arr)
print("Integral part:", integral_part)
print("Fractional part:", fractional_part)


Array: [-2.5  2.5  3.   4.2 -3.7]
Integral part: [-3.  2.  3.  4. -4.]
Fractional part: [0.5 0.5 0.  0.2 0.3]


In [10]:
newVar = np.zeros(5)
newVar[-1] = 1
newVar[1:-1]

array([0., 0., 0.])