<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/LpInCvxpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cvxpy as cp

# Life Improvement
### Abbas Mohammaiyan
### 810898059

_____
_____

# Q1 : Appropriate Diet

##DATA

In [2]:
N = 10
M = 5


B = np.array([100.8, 52.1, 370.8, 200.5, 140 ])
C = np.array([45.79, 30.86, 50.2 , 99.26, 32.17, 42.9 , 66.89, 35.06, 13.78, 53.78])
P = np.array([
    [ 70,  5.12,  8.02,  1.89, 12.25],
    [0,  100,  7.62,  2.34, 17.48],
    [ 6.53, 0.1,  7.89,  200,  0.56],
    [0, 0.1,  0.896,  400, 0],
    [18.23,  1.  , 10.29,  9.21,  0.92],
    [ 2.45,  2.93,  2.24,  4.55,  8.87],
    [ 9.41, 13.1 ,  7.24,  0.24,  7.35],
    [19.21,  1.32, 12.35, 11.22,  5.14],
    [ 1.27, 11.66,  256,  1.14,  2.42],
    [11.37, 17.86,  33, 0,  100]
    ]).T


## Modeling and Solve

In [3]:
x = cp.Variable(10)  # Ten variables: x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9]

# Define the objective function and constraints
objective = cp.Minimize(C.T@x)
constraints = [P @ x >= B, x >= 0]  # Matrix-vector multiplication for constraints

# Define the problem
problem = cp.Problem(objective, constraints)

# Solve the problem
problem.solve()

# Print the optimal value and the optimal variables
print("Optimal value:", problem.value)
print("Optimal x:", x.value)


Optimal value: 186.1597507670487
Optimal x: [ 1.12976430e+00  1.03655415e-01  9.83634850e-01  2.89680010e-09
 -1.12836287e-10 -1.05182770e-09 -6.95104426e-10 -9.97291329e-11
  1.22387781e+00  1.20835871e+00]


In [4]:
C.T@x.value

186.1597507670487

In [5]:
print((P@x.value).reshape(-1,1))
print(B.reshape(-1,1))

[[100.80000003]
 [ 52.10000002]
 [370.80000052]
 [200.50000006]
 [140.00000003]]
[[100.8]
 [ 52.1]
 [370.8]
 [200.5]
 [140. ]]


# Q2 : Project Management

## DATA:

In [6]:
N = 5
p = 2500
t = 800
R = 200
C = np.array([2,  2.09,  4.45, 5.55,  1.52])
T = np.array([3.57,  2.448, 2.69, 3.03,  9.55])
P = np.array([100,8,35,90,20])

In [7]:
# let's aggregate the constraint to have a consolidated matrix
A = np.array([T, np.ones(N), -P])
B = np.array([t, R, -p])

In [8]:
A

array([[   3.57 ,    2.448,    2.69 ,    3.03 ,    9.55 ],
       [   1.   ,    1.   ,    1.   ,    1.   ,    1.   ],
       [-100.   ,   -8.   ,  -35.   ,  -90.   ,  -20.   ]])

## Modeling and Solve

In [9]:
x = cp.Variable(5)  # Five variables: x[0], x[1], x[2], x[3], x[4]

# Define the objective function and constraints
objective = cp.Minimize(C.T@x)

constraints = [A @ x <= B, x >= 0]  # Matrix-vector multiplication for constraints

# Define the problem
problem = cp.Problem(objective, constraints)

# Solve the problem
problem.solve()

# Print the optimal value and the optimal variables
print("Optimal value:", problem.value)
print("Optimal x:", x.value)


Optimal value: 50.000000020910484
Optimal x: [2.50000000e+01 2.28367836e-09 1.08494807e-09 9.31524623e-10
 1.12720847e-09]


In [10]:
print((A@x.value).reshape(-1,1))
print(B.reshape(-1,1))

[[   89.25000003]
 [   25.00000001]
 [-2500.00000038]]
[[  800]
 [  200]
 [-2500]]


# Q3 : Portfolio Selection

## DATA

In [11]:
mu = np.array([19.12, 13.31, 18.4 , 19.56, 18.7 , 14.04, 15.21, 17.74, 19.88, 19.39])
Sigma = np.array([
    [3.44, 2.76, 2.28, 2.35, 2.83, 1.98, 2.22, 2.65, 3.37, 2.49],
    [2.76, 3.68, 2.74, 2.26, 3.06, 1.73, 2.38, 2.16, 2.79, 2.13],
    [2.28, 2.74, 2.62, 1.66, 2.72, 1.43, 2.28, 2.04, 2.35, 1.8 ],
    [2.35, 2.26, 1.66, 2.88, 1.88, 2.14, 2.23, 2.12, 2.59, 2.71],
    [2.83, 3.06, 2.72, 1.88, 3.51, 1.69, 2.34, 2.48, 3.06, 2.13],
    [1.98, 1.73, 1.43, 2.14, 1.69, 2.82, 1.64, 2.57, 2.81, 2.26],
    [2.22, 2.38, 2.28, 2.23, 2.34, 1.64, 2.82, 1.92, 2.33, 2.57],
    [2.65, 2.16, 2.04, 2.12, 2.48, 2.57, 1.92, 3.06, 3.19, 2.24],
    [3.37, 2.79, 2.35, 2.59, 3.06, 2.81, 2.33, 3.19, 3.9 , 2.8 ],
    [2.49, 2.13, 1.8 , 2.71, 2.13, 2.26, 2.57, 2.24, 2.8 , 3.26]
       ])

In [14]:
mu.shape

(10,)

## Modeling and Solve

In [27]:
x = cp.Variable(len(mu))  # Ten variables: x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9]
l = 1 # l means lambda
# Define the objective function and constraints

objective = cp.Maximize(mu.T @ x - l * cp.quad_form(x, Sigma))
constraints = [cp.sum(x) == 1, x >= 0, x <= 1]

# Define the problem
problem = cp.Problem(objective, constraints)

# Solve the problem
problem.solve()

# Print the optimal value and the optimal variables
print("Optimal value:", problem.value)
print("Optimal x:", np.round(x.value, 4))


Optimal value: 16.890606899825922
Optimal x: [-0.     -0.      0.2307  0.6294 -0.      0.     -0.      0.      0.14
 -0.    ]


In [31]:
print("Profit", mu.T@x.value)
print("Risk", x.value.T@Sigma@x.value)

Profit 19.337233739515746
Risk 2.446626839689825


In [32]:
for l in np.arange(0.5, 5, 0.5):
  objective = cp.Maximize(mu.T @ x - l * cp.quad_form(x, Sigma))
  problem = cp.Problem(objective, constraints)

  # Solve the problem
  problem.solve()

  # Print the optimal value and the optimal variables
  print("Lambda = :", l)
  print("Optimal value:", problem.value)
  print("Optimal x:", np.round(x.value, 3))



Lambda = : 0.5
Optimal value: 18.23628125
Optimal x: [ 0.     0.     0.     0.619  0.     0.     0.     0.     0.381 -0.   ]
Lambda = : 1.0
Optimal value: 16.890606899825922
Optimal x: [-0.    -0.     0.231  0.629 -0.     0.    -0.     0.     0.14  -0.   ]
Lambda = : 1.5
Optimal value: 15.718457693727911
Optimal x: [-0.     0.     0.374  0.607 -0.     0.     0.    -0.     0.019 -0.   ]
Lambda = : 2.0
Optimal value: 14.593486238532106
Optimal x: [-0.     0.     0.427  0.573  0.     0.     0.     0.     0.     0.   ]
Lambda = : 2.5
Optimal value: 13.479431192660549
Optimal x: [ 0.     0.     0.453  0.547  0.     0.     0.     0.    -0.     0.   ]
Lambda = : 3.0
Optimal value: 12.370519877675838
Optimal x: [-0.     0.     0.471  0.529  0.    -0.    -0.    -0.    -0.    -0.   ]
Lambda = : 3.5
Optimal value: 11.264547837483615
Optimal x: [-0.    -0.     0.484  0.516 -0.    -0.    -0.    -0.    -0.    -0.   ]
Lambda = : 4.0
Optimal value: 10.1604128440367
Optimal x: [-0.    -0.     0.493  0.