<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/manifoleWarmUp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# to be asked:
# 1- why manifold?!
# 2- what's the benefit
## 3- what do you think of pymanopt?
## 4- what's jax
## 5- what's our job?!

# pystop

## Their examples


In [ ]:
!pip install pystop

In [ ]:
import numpy as np
import scipy as sp
from scipy.sparse import diags
from scipy.sparse.linalg import spsolve

# Import manifolds and solvers
from pystop.manifold import Stiefel
from pystop.solver import SLPG_smooth


# Set parameters
n = 1000
p = 10
alpha = 1
M = Stiefel(n,p)

# Defining objective function
L = diags(np.array([-1, 2, -1]), np.array([1, 0, -1]), shape = (n,n)).tocsc()
def obj_fun(X):
    LX = L@X
    rho = np.sum(X * X, 1)
    Lrho = spsolve(L, rho)
    fval = 0.5*np.sum(X* LX) + (alpha /4) * np.sum(rho * Lrho)
    grad = LX + alpha * Lrho[: ,np.newaxis] * X
    return  fval, grad

# Execute the solver
X, out_dict = SLPG_smooth(obj_fun, M)

Iter:0    fval:2.063e+03   kkts:1.159e+03    feas:1.185043e-15
Iter:20    fval:3.627e+01   kkts:5.586e-01    feas:3.858664e-12
Iter:40    fval:3.572e+01   kkts:2.523e-01    feas:1.942428e-06
Iter:60    fval:3.571e+01   kkts:3.457e-03    feas:6.833490e-16
Iter:80    fval:3.571e+01   kkts:2.094e-04    feas:6.381039e-16
Post-processing
Iter:99    fval:3.571e+01   kkts:7.215e-05    feas:4.225027e-15


In [ ]:
X, out_dict

(array([[-3.27683618e-01, -3.25540636e-01,  5.41405697e-01, ...,
          6.32165439e-02,  3.31662496e-01, -1.33979919e-02],
        [-2.72041204e-01, -3.49550636e-01,  2.24965150e-01, ...,
         -3.44141295e-01, -1.27199354e-01, -4.04717115e-01],
        [ 2.86749830e-01, -3.32543383e-01,  2.68795589e-01, ...,
          5.60008709e-01,  1.77530588e-01,  3.37919986e-01],
        ...,
        [ 4.31898847e-01,  4.73206913e-02,  1.75190041e-01, ...,
         -4.71157583e-01,  4.80237306e-01,  1.27135851e-01],
        [ 2.83050405e-01, -7.98202832e-02,  3.65125622e-01, ...,
         -4.54184393e-01, -2.43508018e-01,  2.67341972e-01],
        [ 5.73889292e-02, -5.16613406e-01, -2.83687629e-04, ...,
          1.29013130e-01, -4.06575168e-01,  3.78201670e-02]]),
 {'kkts': [1159.2674500945334,
   1158.534968886471,
   1157.8001369727324,
   863.895912016348,
   490.82191631629485,
   286.14938802629223,
   171.75993095279162,
   105.23512950024833,
   63.710599772942984,
   37.54965036661

In [ ]:
import autograd.numpy as anp
import numpy as np

n = 1000
p = 30
Z = np.random.randn(n, p)

def obj_fun(X):
    return  anp.sum((X-Z) **2 )


from pystop.utility import fun_autodiff

obj_grad, obj_fungrad = fun_autodiff(obj_fun)


from pystop.manifold import Stiefel
from pystop.solver import SLPG_smooth

M = Stiefel(n,p)
X, out_dict = SLPG_smooth(obj_fungrad, M)

Iter:0    fval:3.014e+04   kkts:3.442e+02    feas:1.846041e-15
Iter:20    fval:2.823e+04   kkts:2.903e-02    feas:1.731237e-15
Iter:25    fval:2.823e+04   kkts:2.832e-07    feas:5.472330e-16
Post-processing
Iter:25    fval:2.823e+04   kkts:2.832e-07    feas:5.053413e-15


In [ ]:
X, out_dict

(array([[ 4.13619129e-02,  4.65445359e-03,  3.50673785e-02, ...,
          5.37125776e-02,  4.85622307e-02,  8.45124551e-03],
        [ 3.95425131e-03,  5.58142113e-02,  2.68919797e-02, ...,
         -3.74205295e-02, -6.25930776e-04, -4.48808267e-03],
        [ 6.83067617e-03,  1.27919523e-02,  2.75009194e-02, ...,
         -6.70366148e-02, -8.86013899e-03, -9.72498393e-05],
        ...,
        [-1.95678193e-03,  1.37402711e-02,  9.31090205e-03, ...,
         -1.41703621e-02, -1.76756708e-02,  2.09892934e-03],
        [ 2.26889048e-02, -1.27487955e-02, -1.08777633e-02, ...,
          2.40521990e-02, -3.53659664e-02, -5.31025983e-02],
        [ 5.42513396e-02,  4.19917174e-03,  3.64187284e-02, ...,
          4.59403091e-02,  7.06900004e-03, -3.10154271e-03]]),
 {'kkts': [344.23524486386026,
   344.23697283739716,
   344.23841696854674,
   344.2413525338116,
   344.2406316130044,
   344.2396286910295,
   344.2358081452929,
   344.2243563957379,
   344.18890625533766,
   344.079729529975

## Little Modifications

In [ ]:
import numpy as np
import scipy as sp
from scipy.sparse import diags
from scipy.sparse.linalg import spsolve
from pystop.manifold import Stiefel
from pystop.solver import SLPG_smooth

# Set parameters
n = 1000
p = 10
alpha = 1
beta = 0.5  # New regularization parameter
M = Stiefel(n, p)

# Defining the sparse matrix L
L = diags(np.array([-1, 2, -1]), np.array([1, 0, -1]), shape=(n, n)).tocsc()

# Modified objective function
def obj_fun(X):
    LX = L @ X
    rho = np.sum(X * X, axis=1)
    Lrho = spsolve(L, rho)

    # Objective function value
    fval = 0.5 * np.sum(X * LX) + (alpha / 4) * np.sum(rho * Lrho) + (beta / 2) * np.sum(X ** 2)

    # Gradient
    grad = LX + alpha * Lrho[:, np.newaxis] * X + beta * X

    return fval, grad

# Execute the solver
X, out_dict = SLPG_smooth(obj_fun, M)


Iter:0    fval:2.091e+03   kkts:1.155e+03    feas:1.023550e-15
Iter:20    fval:3.855e+01   kkts:4.278e-01    feas:1.565698e-10
Iter:40    fval:3.825e+01   kkts:1.482e-01    feas:7.027081e-06
Iter:60    fval:3.821e+01   kkts:2.312e-02    feas:9.668372e-16
Iter:80    fval:3.821e+01   kkts:7.372e-04    feas:6.921568e-16
Post-processing
Iter:99    fval:3.821e+01   kkts:2.941e-05    feas:3.725973e-15


In [ ]:
X, out_dict

(array([[ 0.09208428,  0.82506032,  0.14175073, ...,  0.04425778,
         -0.13918935, -0.08606129],
        [ 0.7842263 ,  0.0349428 , -0.17498969, ...,  0.05668521,
         -0.07851037, -0.09612904],
        [-0.073556  ,  0.06530551, -0.63393806, ...,  0.26900179,
         -0.54875104,  0.38464428],
        ...,
        [ 0.03163435, -0.25768529, -0.21542563, ...,  0.15049503,
          0.06634566,  0.04570063],
        [-0.14774652, -0.22559165, -0.32331305, ...,  0.18654533,
          0.06185747, -0.67500684],
        [ 0.21124565,  0.18822354, -0.39185508, ...,  0.12925791,
          0.77179397,  0.20661216]]),
 {'kkts': [1155.205681659067,
   1154.5263031167347,
   1153.844476771419,
   881.8061467231862,
   507.50579837297926,
   298.6014180517072,
   180.51091579605375,
   109.36656008972983,
   64.82737298642826,
   37.4820077609343,
   21.39764881896494,
   12.12202650410957,
   6.6793399850491495,
   4.106309468482802,
   3.283904601314839,
   2.685125326493077,
   1.6288

In [ ]:
import numpy as np
from pystop.manifold import Stiefel
from pystop.solver import SLPG_smooth

# Set parameters
n = 1000
p = 10
M = Stiefel(n, p)

# Sphere function and its gradient
def obj_fun(X):
    fval = np.sum(X ** 2)
    grad = 2 * X
    return fval, grad

# Execute the solver
X, out_dict = SLPG_smooth(obj_fun, M)


Iter:0    fval:1.000e+01   kkts:7.022e-16    feas:3.489416e-16
Iter:0    fval:1.000e+01   kkts:7.022e-16    feas:3.489416e-16
Post-processing
Iter:0    fval:1.000e+01   kkts:4.983e-15    feas:2.479023e-15


In [ ]:
X, out_dict

(array([[-0.01209938,  0.03667068,  0.0002195 , ...,  0.00159878,
          0.01532198, -0.04009826],
        [ 0.06984943, -0.04942651,  0.02770479, ..., -0.04499692,
          0.0667198 , -0.02905363],
        [-0.00391187,  0.04110945, -0.00372851, ..., -0.0303928 ,
         -0.04644847,  0.03948772],
        ...,
        [ 0.01109772, -0.05552089, -0.03125296, ..., -0.00511709,
          0.04614131, -0.00856444],
        [ 0.00410286, -0.02378133, -0.00602704, ...,  0.03241352,
          0.04716864,  0.02177257],
        [ 0.04089299,  0.03810616, -0.07540142, ...,  0.03140663,
         -0.01200394,  0.00337855]]),
 {'kkts': [4.983057323776491e-15],
  'fvals': [10.000000000000002],
  'fea': 2.479023296880616e-15,
  'kkt': 4.983057323776491e-15,
  'fval': 10.000000000000002,
  'feas': [2.479023296880616e-15]})

# pymanopt

In [11]:
!pip uninstall -y jax jaxlib pymanopt
!pip install jax==0.3.25 jaxlib==0.3.25
!pip install pymanopt==2.2.0

import pymanopt


Found existing installation: pymanopt 0.2.5
Uninstalling pymanopt-0.2.5:
  Successfully uninstalled pymanopt-0.2.5
  Using cached jax-0.3.25-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.25 (from versions: 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30)
ERROR: No matching distribution found for jaxlib==0.3.25
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 1.2 MB/s eta 0:00:00


In [3]:
import autograd.numpy as anp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

anp.random.seed(42)

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = anp.random.normal(size=(dim, dim))
matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = anp.linalg.eig(matrix)
dominant_eigenvector = eigenvectors[:, eigenvalues.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +1.1041943339110254e+00    5.65626470e-01    
   2         +5.2849633289004561e-01    8.90742722e-01    
   3         -8.0741058657312559e-01    2.23937710e+00    
   4         -1.2667369971251594e+00    1.59671326e+00    
   5         -1.4100298597091836e+00    1.11228845e+00    
   6         -1.5219408277812503e+00    2.45507203e-01    
   7         -1.5269956262562046e+00    6.81712914e-02    
   8         -1.5273114803528711e+00    3.40941735e-02    
   9         -1.5273905588875485e+00    1.70222768e-02    
  10         -1.5274100956128573e+00    8.61140952e-03    
  11         -1.5274154319869830e+00    3.90706914e-03    
  12         -1.5274156215853552e+00    3.62943720e-03    
  13         -1.5274162595152965e+00    2.47643447e-03    
  14         -1.5274168030609059e+00    3.66398563e-04    
  15         -1.5274168133149573e+00    1.

In [4]:
!pip show pymanopt

Name: pymanopt
Version: 2.2.0
Summary: Toolbox for optimization on Riemannian manifolds with support for automatic differentiation
Home-page: https://pymanopt.org
Author: Jamie Townsend, Niklas Koep, Sebastian Weichwald
Author-email: 
License: BSD 3-Clause License
Location: /usr/local/lib/python3.10/dist-packages
Requires: numpy, scipy
Required-by: 
