<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/TotalLeastSquaresMonifold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparation and Test

In [1]:
!pip uninstall -y jax jaxlib pymanopt
!pip install jax==0.3.25 jaxlib==0.3.25
!pip install pymanopt==2.2.0

import pymanopt
import numpy as np

Found existing installation: jax 0.4.26
Uninstalling jax-0.4.26:
  Successfully uninstalled jax-0.4.26
Found existing installation: jaxlib 0.4.26+cuda12.cudnn89
Uninstalling jaxlib-0.4.26+cuda12.cudnn89:
  Successfully uninstalled jaxlib-0.4.26+cuda12.cudnn89
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.25 (from versions: 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30)
ERROR: No matching distribution found for jaxlib==0.3.25
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 762.9 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 34.1 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.4
    Uninstalling scipy-1.11.4:
      Successfully

In [2]:
!pip install jax
import jax

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 MB 6.2 MB/s eta 0:00:00


In [3]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))
# matrix = anp.random.normal(size=(dim, dim))
matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +3.2806330919265747e-01    1.02998907e-01    
   2         -5.5424314737319946e-01    1.79739235e+00    
   3         -1.3646783828735352e+00    1.01401240e+00    
   4         -1.5016909837722778e+00    3.28524848e-01    
   5         -1.5160342454910278e+00    5.33937300e-02    
   6         -1.5164102315902710e+00    8.60075919e-03    
   7         -1.5164198875427246e+00    1.48993958e-03    
   8         -1.5164198875427246e+00    1.50194636e-03    
Terminated - min step_size reached after 8 iterations, 0.18 seconds.

Dominant eigenvector: [0.70809877+0.j 0.49849728+0.j 0.5000967 +0.j]
Pymanopt solution: [-0.70828517 -0.49858428 -0.49974577]


# Manopt first function

In [4]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -1.3378024101257324e+00    1.02247125e+00    
   2         -1.4851963520050049e+00    4.67262634e-01    
   3         -1.5151474475860596e+00    9.69016064e-02    
   4         -1.5161383152008057e+00    4.56268462e-02    
   5         -1.5162587165832520e+00    3.45555424e-02    
   6         -1.5163815021514893e+00    1.69115991e-02    
   7         -1.5164071321487427e+00    9.90219666e-03    
   8         -1.5164089202880859e+00    9.21612100e-03    
   9         -1.5164148807525635e+00    6.34984635e-03    
  10         -1.5164202451705933e+00    5.83682085e-04    
  11         -1.5164202451705933e+00    4.77047790e-04    
Terminated - min step_size reached after 11 iterations, 0.02 seconds.

Dominant eigenvector: [0.70809877+0.j 0.49849728+0.j 0.5000967 +0.j]
Pymanopt solution: [-0.70815803 -0.49852485 -0.49998518]


In [5]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)
print("Pymanopt solution verification:","\n", result.point.T@result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -6.6699314117431641e-01    1.17026621e+00    
   2         -2.0085303783416748e+00    1.61735580e+00    
   3         -2.1370377540588379e+00    1.88444207e+00    
   4         -2.5410444736480713e+00    1.09218383e+00    
   5         -2.6863398551940918e+00    4.68991253e-01    
   6         -2.7138514518737793e+00    2.25878362e-01    
   7         -2.7138881683349609e+00    2.76486166e-01    
   8         -2.7140340805053711e+00    2.74106971e-01    
   9         -2.7146077156066895e+00    2.64567629e-01    
  10         -2.7167334556579590e+00    2.25680614e-01    
  11         -2.7220458984375000e+00    5.71628906e-02    
  12         -2.7222049236297607e+00    4.67750562e-02    
  13         -2.7224264144897461e+00    1.50375984e-02    
  14         -2.7224516868591309e+00    2.50416112e-03    
  15         -2.7224526405334473e+00    2.

In [6]:
result.point.T@ result.point

array([[ 1.00000000e+00,  2.61859240e-17, -1.22688906e-17],
       [ 2.61859240e-17,  1.00000000e+00, -6.74633312e-17],
       [-1.22688906e-17, -6.74633312e-17,  1.00000000e+00]])

# Final Code:)

In [7]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random

## one iteration

In [8]:
def TLS(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]
  print(m, n)
  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)
  sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
  S = np.diag(sRow)
  print(S)
  manifold = pymanopt.manifolds.Stiefel(n, r)

  @pymanopt.function.autograd(manifold)
  def cost(Y):
    return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))


  problem = pymanopt.Problem(manifold, cost)

  optimizer = pymanopt.optimizers.SteepestDescent()
  result = optimizer.run(problem)
  print(result.point.T@result.point)
  return result.point

In [9]:
d = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
TLS(d, t, 2)

6 3
[[1.014837   0.        ]
 [0.         0.99399901]]
Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +1.7105247974395752e+00    1.22123844e+00    
   2         +5.7832336425781250e-01    9.90731397e-01    
   3         +4.7587585449218750e-01    6.57816331e-01    
   4         +4.2311096191406250e-01    3.29148812e-01    
   5         +4.0956115722656250e-01    2.14369207e-01    
   6         +4.0476989746093750e-01    2.06772098e-01    
   7         +3.9801025390625000e-01    1.24920087e-01    
   8         +3.9746093750000000e-01    2.04685487e-01    
   9         +3.9543151855468750e-01    1.71615928e-01    
  10         +3.9062500000000000e-01    6.11771995e-02    
  11         +3.8517761230468750e-01    1.54421415e-01    
  12         +3.8200378417968750e-01    6.25221949e-02    
  13         +3.8143920898437500e-01    1.74826506e-02    
  14         +3.8133239746093750e-01    8.8735

array([[-0.84767982, -0.16145842],
       [-0.48438446, -0.15292549],
       [ 0.21635759, -0.97495896]])

## multiple iterations

In [37]:
def TLSm(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]

  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)

  manifold = pymanopt.manifolds.Stiefel(n, r)




  # for must be transfered to while but since I don't know the threshold, I'll do it later
  for i in range(40):
    sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
    S = np.diag(sRow)
    @pymanopt.function.autograd(manifold)
    def cost(Y):
      return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))
    problem = pymanopt.Problem(manifold, cost)

    optimizer = pymanopt.optimizers.SteepestDescent()
    result = optimizer.run(problem)
    Y = result.point
    print("*****************","\n",S,"\n","***************")
  print(result.point.T@result.point)
  return result.point, S

In [38]:
d = jnp.array([[1.9, 2.1, 3], [4.9, 9, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1.1, 2.9, 3], [3.8, 7, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
TLSm(d, t, 3)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +6.6045379638671875e+00    8.30501502e-01    
   2         +6.4925765991210938e+00    6.59872484e-01    
   3         +6.4579772949218750e+00    5.03467771e-01    
   4         +6.4496765136718750e+00    4.53642440e-01    
   5         +6.4259757995605469e+00    1.95660502e-01    
   6         +6.4205474853515625e+00    3.04885455e-02    
   7         +6.4202728271484375e+00    3.84845699e-02    
   8         +6.4202041625976562e+00    5.75800244e-02    
   9         +6.4199218750000000e+00    4.33348794e-02    
  10         +6.4198074340820312e+00    4.83649994e-02    
  11         +6.4193878173828125e+00    2.59136411e-02    
  12         +6.4189453125000000e+00    5.03957324e-02    
  13         +6.4188995361328125e+00    6.98626005e-02    
  14         +6.4188003540039062e+00    6.18030242e-02    
  15         +6.4183807373046875e+00    4.

(array([[-0.45679313,  0.03661813, -0.88881896],
        [-0.57409765,  0.75109345,  0.32599158],
        [-0.67952331, -0.65917959,  0.32207194]]),
 array([[0.98577789, 0.        , 0.        ],
        [0.        , 0.71473164, 0.        ],
        [0.        , 0.        , 1.18538461]]))

In [39]:
TLSm(d, t, 2)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +5.9465942382812500e+00    3.28584835e+00    
   2         +3.2383728027343750e+00    2.26750026e+00    
   3         +3.1222610473632812e+00    2.32592907e+00    
   4         +2.8077297210693359e+00    1.10588434e+00    
   5         +2.6634640693664551e+00    7.52018527e-01    
   6         +2.6322152614593506e+00    2.06705505e-01    
   7         +2.6294093132019043e+00    1.25726865e-01    
   8         +2.6287803649902344e+00    8.35096178e-02    
   9         +2.6286854743957520e+00    5.98537927e-02    
  10         +2.6284112930297852e+00    3.38035579e-03    
  11         +2.6283907890319824e+00    2.81623976e-03    
  12         +2.6283862590789795e+00    2.79252691e-03    
  13         +2.6283810138702393e+00    2.79248574e-03    
  14         +2.6283495426177979e+00    2.78638377e-03    
  15         +2.6283495426177979e+00    2.

(array([[-0.38938928, -0.87896501],
        [ 0.11687751,  0.24933509],
        [-0.91362773,  0.40651263]]),
 array([[1.00068591, 0.        ],
        [0.        , 1.21678472]]))

# junk

In [ ]:
# def TLS(D, T, r):
D = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
T = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
r = 2

if D.shape != T.shape:
  raise ValueError("Dimension mismatch")

m, n = D.shape[0], D.shape[1]

A = D.T @ D
B = T.T @ T
C = D.T @ T + T.T @ D
Y = np.zeros((n, r)) # it may need conversion to jax
Y[:r,:] = np.eye(r)
sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
S = np.diag(sRow)

manifold = pymanopt.manifolds.Stiefel(n, r)


@pymanopt.function.autograd(manifold)
def cost(Y):
  return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))

problem = pymanopt.Problem(manifold, cost)
optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)
print(result.point)
print(result.point.T@result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +5.3538513183593750e-01    9.44420518e-01    
   2         +4.5117187500000000e-01    6.06402528e-01    
   3         +4.0443420410156250e-01    3.13780643e-01    
   4         +3.9474487304687500e-01    2.07396572e-01    
   5         +3.8940429687500000e-01    1.24909543e-01    
   6         +3.8690185546875000e-01    5.20929660e-02    
   7         +3.8598632812500000e-01    1.34784161e-01    
   8         +3.8356018066406250e-01    4.67923577e-02    
   9         +3.8305664062500000e-01    4.37475867e-02    
  10         +3.8265991210937500e-01    3.82358003e-02    
  11         +3.8246154785156250e-01    3.49117164e-02    
  12         +3.8232421875000000e-01    4.13730679e-02    
  13         +3.8200378417968750e-01    1.70396839e-02    
  14         +3.8175964355468750e-01    3.75910259e-02    
  15         +3.8157653808593750e-01    1.

In [ ]:
# prompt: make a 2by 2 matrix and raise it to the power of -2

import numpy as np

matrix = np.array([[1, 2], [3, 4]])
inverse_squared = np.linalg.matrix_power(matrix, -2)

print(inverse_squared@np.linalg.matrix_power(matrix, 2))


[[ 1.00000000e+00 -8.88178420e-15]
 [ 3.99680289e-15  1.00000000e+00]]


In [ ]:

key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -1.0553249120712280e+00    1.50072370e+00    
   2         -1.9962484836578369e+00    5.55656854e-01    
   3         -2.1164600849151611e+00    1.86524587e+00    
   4         -2.5033340454101562e+00    1.15338850e+00    
   5         -2.5297145843505859e+00    1.24785336e+00    
   6         -2.6212491989135742e+00    9.17485706e-01    
   7         -2.6574642658233643e+00    7.52870204e-01    
   8         -2.7211558818817139e+00    9.86398166e-02    
   9         -2.7217109203338623e+00    8.02943698e-02    
  10         -2.7222251892089844e+00    4.47678073e-02    
  11         -2.7224435806274414e+00    7.96516622e-03    
  12         -2.7224478721618652e+00    6.93928798e-03    
  13         -2.7224509716033936e+00    4.24068955e-03    
  14         -2.7224526405334473e+00    2.37614942e-03    
  15         -2.7224528789520264e+00    8.