<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/TotalLeastSquaresMonifold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparation and Test

In [6]:
!pip uninstall -y jax jaxlib pymanopt
!pip install jax==0.3.25 jaxlib==0.3.25
!pip install pymanopt==2.2.0

import pymanopt
import numpy as np

Found existing installation: jax 0.4.30
Uninstalling jax-0.4.30:
  Successfully uninstalled jax-0.4.30
Found existing installation: jaxlib 0.4.30
Uninstalling jaxlib-0.4.30:
  Successfully uninstalled jaxlib-0.4.30
Found existing installation: pymanopt 2.2.0
Uninstalling pymanopt-2.2.0:
  Successfully uninstalled pymanopt-2.2.0
  Using cached jax-0.3.25.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.25 (from versions: 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30)
ERROR: No matching distribution found for jaxlib==0.3.25
  Using cached pymanopt-2.2.0-py3-none-any.whl (71 kB)


In [7]:
!pip install jax
import jax

  Using cached jax-0.4.30-py3-none-any.whl (2.0 MB)
  Using cached jaxlib-0.4.30-cp310-cp310-manylinux2014_x86_64.whl (79.6 MB)


In [8]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))
# matrix = anp.random.normal(size=(dim, dim))
matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -5.9247386455535889e-01    1.65398824e+00    
   2         -1.4880242347717285e+00    4.11089230e-01    
   3         -1.4908581972122192e+00    3.96044154e-01    
   4         -1.5009369850158691e+00    3.08355832e-01    
   5         -1.5147876739501953e+00    1.05029515e-01    
   6         -1.5163927078247070e+00    1.40678374e-02    
   7         -1.5164012908935547e+00    1.17809382e-02    
   8         -1.5164201259613037e+00    1.18396278e-03    
   9         -1.5164203643798828e+00    5.70089985e-04    
  10         -1.5164203643798828e+00    1.95245770e-04    
Terminated - min step_size reached after 10 iterations, 0.03 seconds.

Dominant eigenvector: [0.70809877+0.j 0.49849728+0.j 0.5000967 +0.j]
Pymanopt solution: [-0.70807701 -0.49848219 -0.50014244]


# Manopt first function

In [9]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +3.2788020372390747e-01    6.15143996e-02    
   2         +2.8173908591270447e-02    8.57816175e-01    
   3         -1.1289234161376953e+00    1.29837469e+00    
   4         -1.1504622697830200e+00    1.27425449e+00    
   5         -1.2328430414199829e+00    1.16259998e+00    
   6         -1.4703366756439209e+00    5.13238650e-01    
   7         -1.5127818584442139e+00    1.46345734e-01    
   8         -1.5156599283218384e+00    6.69733389e-02    
   9         -1.5158150196075439e+00    5.97735982e-02    
  10         -1.5162764787673950e+00    2.91367210e-02    
  11         -1.5163676738739014e+00    1.76237832e-02    
  12         -1.5163918733596802e+00    1.29829456e-02    
  13         -1.5164062976837158e+00    9.15287476e-03    
  14         -1.5164202451705933e+00    5.72390387e-04    
  15         -1.5164203643798828e+00    1.

In [10]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)
print("Pymanopt solution verification:","\n", result.point.T@result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -1.9844378232955933e+00    5.17663507e-01    
   2         -2.0758011341094971e+00    1.58394074e+00    
   3         -2.3777084350585938e+00    1.07915217e+00    
   4         -2.5899252891540527e+00    8.78915068e-01    
   5         -2.6114149093627930e+00    9.64334654e-01    
   6         -2.6807394027709961e+00    5.91983724e-01    
   7         -2.7009329795837402e+00    4.35406964e-01    
   8         -2.7055540084838867e+00    3.89248067e-01    
   9         -2.7189812660217285e+00    1.76361128e-01    
  10         -2.7193603515625000e+00    1.67183328e-01    
  11         -2.7206907272338867e+00    1.26201990e-01    
  12         -2.7219915390014648e+00    6.46322920e-02    
  13         -2.7223753929138184e+00    2.65303879e-02    
  14         -2.7224488258361816e+00    6.26401424e-03    
  15         -2.7224531173706055e+00    5.

In [11]:
result.point.T@ result.point

array([[ 1.00000000e+00,  6.40532040e-17, -2.61567679e-17],
       [ 6.40532040e-17,  1.00000000e+00,  1.70518475e-16],
       [-2.61567679e-17,  1.70518475e-16,  1.00000000e+00]])

# Final Code:)

In [12]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random

## one iteration

In [89]:
def TLS(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]
  print(m, n)
  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)
  sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
  S = np.diag(sRow)
  print(S)
  manifold = pymanopt.manifolds.Stiefel(n, r)

  @pymanopt.function.autograd(manifold)
  def cost(Y):
    return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))


  problem = pymanopt.Problem(manifold, cost)

  optimizer = pymanopt.optimizers.SteepestDescent()
  result = optimizer.run(problem)
  print(result.point.T@result.point)
  return result.point

In [90]:
d = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
TLS(d, t, 2)

6 3
[[1.014837   0.        ]
 [0.         0.99399901]]
Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +1.8816280364990234e+00    1.07159051e+00    
   2         +7.7285766601562500e-01    1.34943205e+00    
   3         +7.5433349609375000e-01    1.36952014e+00    
   4         +6.8316650390625000e-01    1.26088531e+00    
   5         +4.6292114257812500e-01    6.90414021e-01    
   6         +3.9604187011718750e-01    2.86826108e-01    
   7         +3.8462829589843750e-01    1.04236612e-01    
   8         +3.8378906250000000e-01    8.61515323e-02    
   9         +3.8288879394531250e-01    5.29173208e-02    
  10         +3.8275146484375000e-01    6.40274015e-02    
  11         +3.8236999511718750e-01    3.72472902e-02    
  12         +3.8214111328125000e-01    3.47356105e-02    
  13         +3.8191223144531250e-01    1.86024119e-02    
  14         +3.8186645507812500e-01    4.0972

array([[-0.84764315,  0.16183381],
       [-0.48494203,  0.15004854],
       [ 0.21524943,  0.97534366]])

## multiple iterations

In [92]:
def TLSm(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]
  print(m, n)
  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)
  sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
  S = np.diag(sRow)
  print(S)
  manifold = pymanopt.manifolds.Stiefel(n, r)

  @pymanopt.function.autograd(manifold)
  def cost(Y):
    return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))


  problem = pymanopt.Problem(manifold, cost)

  optimizer = pymanopt.optimizers.SteepestDescent()
  result = optimizer.run(problem)
  print(result.point.T@result.point)
  return result.point

In [93]:
d = jnp.array([[1.9, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1.1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
TLSm(d, t, 2)

6 3
[[1.01026    0.        ]
 [0.         0.99399901]]
Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +1.9210815429687500e+00    2.83888012e+00    
   2         +1.6545104980468750e-01    6.95155019e-01    
   3         +1.2187194824218750e-01    1.74316082e-01    
   4         +1.1952209472656250e-01    1.67042741e-01    
   5         +1.1723327636718750e-01    1.44611076e-01    
   6         +1.1632537841796875e-01    1.87792859e-01    
   7         +1.1352539062500000e-01    1.01920541e-01    
   8         +1.1258697509765625e-01    1.61419243e-01    
   9         +1.1009216308593750e-01    7.08000043e-02    
  10         +1.0797119140625000e-01    1.52474084e-01    
  11         +1.0665893554687500e-01    1.50123364e-01    
  12         +1.0439300537109375e-01    6.51294553e-02    
  13         +1.0429763793945312e-01    1.85913775e-01    
  14         +1.0382843017578125e-01    1.7551

array([[ 0.51056574,  0.44402224],
       [ 0.52729414,  0.51473294],
       [-0.67917856,  0.73341274]])

# junk

In [87]:
# def TLS(D, T, r):
D = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
T = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
r = 2

if D.shape != T.shape:
  raise ValueError("Dimension mismatch")

m, n = D.shape[0], D.shape[1]

A = D.T @ D
B = T.T @ T
C = D.T @ T + T.T @ D
Y = np.zeros((n, r)) # it may need conversion to jax
Y[:r,:] = np.eye(r)
sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
S = np.diag(sRow)

manifold = pymanopt.manifolds.Stiefel(n, r)


@pymanopt.function.autograd(manifold)
def cost(Y):
  return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))

problem = pymanopt.Problem(manifold, cost)
optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)
print(result.point)
print(result.point.T@result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +5.3538513183593750e-01    9.44420518e-01    
   2         +4.5117187500000000e-01    6.06402528e-01    
   3         +4.0443420410156250e-01    3.13780643e-01    
   4         +3.9474487304687500e-01    2.07396572e-01    
   5         +3.8940429687500000e-01    1.24909543e-01    
   6         +3.8690185546875000e-01    5.20929660e-02    
   7         +3.8598632812500000e-01    1.34784161e-01    
   8         +3.8356018066406250e-01    4.67923577e-02    
   9         +3.8305664062500000e-01    4.37475867e-02    
  10         +3.8265991210937500e-01    3.82358003e-02    
  11         +3.8246154785156250e-01    3.49117164e-02    
  12         +3.8232421875000000e-01    4.13730679e-02    
  13         +3.8200378417968750e-01    1.70396839e-02    
  14         +3.8175964355468750e-01    3.75910259e-02    
  15         +3.8157653808593750e-01    1.

In [60]:
# prompt: make a 2by 2 matrix and raise it to the power of -2

import numpy as np

matrix = np.array([[1, 2], [3, 4]])
inverse_squared = np.linalg.matrix_power(matrix, -2)

print(inverse_squared@np.linalg.matrix_power(matrix, 2))


[[ 1.00000000e+00 -8.88178420e-15]
 [ 3.99680289e-15  1.00000000e+00]]


In [55]:

key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -1.0553249120712280e+00    1.50072370e+00    
   2         -1.9962484836578369e+00    5.55656854e-01    
   3         -2.1164600849151611e+00    1.86524587e+00    
   4         -2.5033340454101562e+00    1.15338850e+00    
   5         -2.5297145843505859e+00    1.24785336e+00    
   6         -2.6212491989135742e+00    9.17485706e-01    
   7         -2.6574642658233643e+00    7.52870204e-01    
   8         -2.7211558818817139e+00    9.86398166e-02    
   9         -2.7217109203338623e+00    8.02943698e-02    
  10         -2.7222251892089844e+00    4.47678073e-02    
  11         -2.7224435806274414e+00    7.96516622e-03    
  12         -2.7224478721618652e+00    6.93928798e-03    
  13         -2.7224509716033936e+00    4.24068955e-03    
  14         -2.7224526405334473e+00    2.37614942e-03    
  15         -2.7224528789520264e+00    8.