<a href="https://colab.research.google.com/github/garfield-gray/Optimization/blob/main/Convex/TotalLeastSquaresMonifold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparation and Test

In [ ]:
!pip uninstall -y jax jaxlib pymanopt
!pip install jax==0.3.25 jaxlib==0.3.25
!pip install pymanopt==2.2.0

import pymanopt
import numpy as np

Found existing installation: pymanopt 2.2.0
Uninstalling pymanopt-2.2.0:
  Successfully uninstalled pymanopt-2.2.0
  Using cached jax-0.3.25.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.25 (from versions: 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30)
ERROR: No matching distribution found for jaxlib==0.3.25
  Using cached pymanopt-2.2.0-py3-none-any.whl (71 kB)


In [ ]:
!pip install jax
import jax

  Using cached jax-0.4.30-py3-none-any.whl (2.0 MB)
  Using cached jaxlib-0.4.30-cp310-cp310-manylinux2014_x86_64.whl (79.6 MB)


In [ ]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))
# matrix = anp.random.normal(size=(dim, dim))
matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -3.0124574899673462e-01    1.15418222e+00    
   2         -1.3396354913711548e+00    9.58307302e-01    
   3         -1.4864025115966797e+00    4.16763872e-01    
   4         -1.5149689912796021e+00    9.27665024e-02    
   5         -1.5163402557373047e+00    2.20710344e-02    
   6         -1.5164192914962769e+00    2.66628699e-03    
   7         -1.5164202451705933e+00    7.22670126e-04    
   8         -1.5164203643798828e+00    4.95651153e-04    
   9         -1.5164203643798828e+00    3.92588935e-04    
Terminated - min step_size reached after 9 iterations, 0.20 seconds.

Dominant eigenvector: [0.70809877+0.j 0.49849728+0.j 0.5000967 +0.j]
Pymanopt solution: [0.70805071 0.49847345 0.50018837]


# Manopt first function

In [ ]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -8.7990939617156982e-01    1.75316735e+00    
   2         -1.4707019329071045e+00    5.73873746e-01    
   3         -1.5001860857009888e+00    3.44758718e-01    
   4         -1.5059131383895874e+00    2.77793556e-01    
   5         -1.5163354873657227e+00    2.50229658e-02    
   6         -1.5163484811782837e+00    2.30441362e-02    
   7         -1.5163910388946533e+00    1.47146025e-02    
   8         -1.5164144039154053e+00    6.64828191e-03    
   9         -1.5164148807525635e+00    6.33135997e-03    
  10         -1.5164165496826172e+00    5.21875848e-03    
  11         -1.5164202451705933e+00    4.94445262e-04    
  12         -1.5164203643798828e+00    3.68160043e-04    
  13         -1.5164203643798828e+00    6.91938276e-05    
Terminated - min step_size reached after 13 iterations, 0.02 seconds.

Dominant eigenvector: [0.70809

In [ ]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random
key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)
print("Pymanopt solution verification:","\n", result.point.T@result.point)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -8.6410832405090332e-01    1.33994694e+00    
   2         -1.8882863521575928e+00    7.44361322e-01    
   3         -1.8917272090911865e+00    1.09683507e+00    
   4         -1.9053658246994019e+00    1.07716281e+00    
   5         -1.9578077793121338e+00    9.97743156e-01    
   6         -2.1286025047302246e+00    7.40385479e-01    
   7         -2.5119981765747070e+00    1.07454949e+00    
   8         -2.6753392219543457e+00    4.65648124e-01    
   9         -2.7098133563995361e+00    2.71031931e-01    
  10         -2.7147154808044434e+00    2.57963626e-01    
  11         -2.7215061187744141e+00    8.70232517e-02    
  12         -2.7216112613677979e+00    8.67722154e-02    
  13         -2.7219786643981934e+00    6.49341596e-02    
  14         -2.7222959995269775e+00    3.75011425e-02    
  15         -2.7224516868591309e+00    2.

In [ ]:
result.point.T@ result.point

array([[ 1.00000000e+00, -7.15477106e-18, -1.28857450e-16],
       [-7.15477106e-18,  1.00000000e+00, -2.33945543e-17],
       [-1.28857450e-16, -2.33945543e-17,  1.00000000e+00]])

# Final Code:)

In [ ]:
import jax.numpy as jnp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

from jax import random

## one iteration

In [ ]:
def TLS(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]
  print(m, n)
  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)
  sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
  S = np.diag(sRow)
  print(S)
  manifold = pymanopt.manifolds.Stiefel(n, r)

  @pymanopt.function.autograd(manifold)
  def cost(Y):
    return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))


  problem = pymanopt.Problem(manifold, cost)

  optimizer = pymanopt.optimizers.SteepestDescent()
  result = optimizer.run(problem)
  print(result.point.T@result.point)
  return result.point

In [ ]:
d = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
TLS(d, t, 2)

## multiple iterations

In [ ]:
def TLSm(D, T, r):
  if D.shape != T.shape:
    raise ValueError("Dimension mismatch")

  m, n = D.shape[0], D.shape[1]

  A = D.T @ D
  B = T.T @ T
  C = D.T @ T + T.T @ D
  Y = np.zeros((n, r)) # it may need conversion to jax
  Y[:r,:] = np.eye(r)

  manifold = pymanopt.manifolds.Stiefel(n, r)




  # for must be transfered to while but since I don't know the threshold, I'll do it later
  X = np.ones((n, n))
  for i in range(80):
    print("iteration: ",i)
    sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
    S = np.diag(sRow)
    @pymanopt.function.autograd(manifold)
    def cost(Y):
      return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))
    problem = pymanopt.Problem(manifold, cost)

    # change verbosity if you wanna see more info
    optimizer = pymanopt.optimizers.SteepestDescent(verbosity = 0)
    result = optimizer.run(problem)
    Y = result.point

    print("*****************","\n",Y @ np.linalg.matrix_power(S, 2) @ Y.T,"\n","***************")
    diff = Y @ np.linalg.matrix_power(S, 2) @ Y.T - X
    print("norm ",np.linalg.norm(diff,'fro'))

    X = Y @ np.linalg.matrix_power(S, 2) @ Y.T
  # print(result.point.T@result.point)
  return Y @ np.linalg.matrix_power(S, 2) @ Y.T

In [ ]:
d = jnp.array([[1.9, 2.1, 3], [4.9, 9, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
t = jnp.array([[1.1, 2.9, 3], [3.8, 7, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
x = TLSm(d, t, 3)

iteration:  0
***************** 
 [[ 0.99667386 -0.01510255  0.00305111]
 [-0.01510255  0.93137537  0.01472772]
 [ 0.00305111  0.01472772  0.98211988]] 
 ***************
norm  2.4485186524160514
iteration:  1
***************** 
 [[ 1.00772599 -0.01674757 -0.00284893]
 [-0.01674757  0.91911002  0.02620297]
 [-0.00284893  0.02620297  0.98085295]] 
 ***************
norm  0.024750553828330104
iteration:  2
***************** 
 [[ 1.07815421 -0.03952138 -0.03293534]
 [-0.03952138  0.91508926  0.04625874]
 [-0.03293534  0.04625874  0.98454565]] 
 ***************
norm  0.09296279390296429
iteration:  3
***************** 
 [[ 1.2910495  -0.09556519 -0.13674874]
 [-0.09556519  0.91669346  0.08615937]
 [-0.13674874  0.08615937  1.02266848]] 
 ***************
norm  0.27892779019178493
iteration:  4
***************** 
 [[ 1.36314329 -0.12062446 -0.16666126]
 [-0.12062446  0.90918932  0.1123797 ]
 [-0.16666126  0.1123797   1.01937563]] 
 ***************
norm  0.09841306734770916
iteration:  5
******

In [ ]:
t

Array([[1.1, 2.9, 3. ],
       [3.8, 7. , 6. ],
       [7. , 8. , 9. ],
       [1. , 2. , 3. ],
       [4.9, 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float32)

In [ ]:
d @ x

Array([[1.8672845, 2.1473145, 2.8117585],
       [4.5045056, 7.797998 , 6.8039064],
       [7.0795407, 7.552608 , 8.7479105],
       [0.690362 , 2.199676 , 2.8887272],
       [3.7706194, 5.486238 , 6.0362787],
       [7.0795407, 7.552608 , 8.7479105]], dtype=float32)

In [ ]:
TLSm(d, t, 2)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +3.8340125083923340e+00    3.82606536e+00    
   2         +3.2381792068481445e+00    2.67351050e+00    
   3         +2.8482036590576172e+00    1.21179655e+00    
   4         +2.7545449733734131e+00    5.53274944e-01    
   5         +2.7042250633239746e+00    1.10430750e+00    
   6         +2.6580286026000977e+00    6.44078308e-01    
   7         +2.6355924606323242e+00    1.42071930e-01    
   8         +2.6315152645111084e+00    2.18399435e-01    
   9         +2.6297948360443115e+00    1.40227558e-01    
  10         +2.6290912628173828e+00    9.57178869e-02    
  11         +2.6286606788635254e+00    4.80618455e-02    
  12         +2.6285808086395264e+00    3.75395971e-02    
  13         +2.6285650730133057e+00    4.15482893e-02    
  14         +2.6285438537597656e+00    2.80633106e-02    
  15         +2.6285006999969482e+00    8.

(array([[-0.37878613, -0.88084043],
        [ 0.11725187,  0.25869134],
        [-0.91802672,  0.39648321]]),
 array([[1.00082025, 0.        ],
        [0.        , 1.2165128 ]]))

# junk

In [ ]:
# def TLS(D, T, r):
D = jnp.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5.8, 6], [7, 8, 9]])
T = jnp.array([[1, 2.9, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4.9, 5, 6], [7, 8, 9]])
r = 2

if D.shape != T.shape:
  raise ValueError("Dimension mismatch")

m, n = D.shape[0], D.shape[1]

A = D.T @ D
B = T.T @ T
C = D.T @ T + T.T @ D
Y = np.zeros((n, r)) # it may need conversion to jax
Y[:r,:] = np.eye(r)
sRow = [np.power(((Y[:,i].T@B@Y[:,i])/(Y[:,i].T@A@Y[:,i])),0.25) for i in range(r)]
S = np.diag(sRow)

manifold = pymanopt.manifolds.Stiefel(n, r)


@pymanopt.function.autograd(manifold)
def cost(Y):
  return np.trace(Y.T @ A @ Y @ np.linalg.matrix_power(S,2)- Y.T@C@Y + Y.T @ B @ Y @ np.linalg.matrix_power(S,-2))

problem = pymanopt.Problem(manifold, cost)
optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)
print(result.point)
print(result.point.T@result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +1.6456909179687500e+00    5.78866054e-01    
   2         +7.6175689697265625e-01    1.16952350e+00    
   3         +4.7988891601562500e-01    6.13324396e-01    
   4         +4.2127990722656250e-01    1.78404957e-01    
   5         +4.1961669921875000e-01    3.11155639e-01    
   6         +4.1366577148437500e-01    2.44878421e-01    
   7         +4.0368652343750000e-01    1.22037233e-01    
   8         +3.9923095703125000e-01    1.35893077e-01    
   9         +3.9550781250000000e-01    1.04117925e-01    
  10         +3.9297485351562500e-01    1.23068321e-01    
  11         +3.9175415039062500e-01    1.51699461e-01    
  12         +3.8836669921875000e-01    6.37391876e-02    
  13         +3.8694763183593750e-01    8.34899769e-02    
  14         +3.8546752929687500e-01    5.06377554e-02    
  15         +3.8500976562500000e-01    1.

In [ ]:
# prompt: make a 2by 2 matrix and raise it to the power of -2

import numpy as np

matrix = np.array([[1, 2], [3, 4]])
inverse_squared = np.linalg.matrix_power(matrix, -2)

print(inverse_squared@np.linalg.matrix_power(matrix, 2))


[[ 1.00000000e+00 -8.88178420e-15]
 [ 3.99680289e-15  1.00000000e+00]]


In [ ]:

key = random.PRNGKey(758493)  # Random seed is explicit in JAX

dim = 4
r = 3
manifold = pymanopt.manifolds.Stiefel(dim, r)

matrix = jax.random.uniform(key, shape=(dim,dim))

matrix = 0.5 * (matrix + matrix.T)


# Defines the cost function cost(X) decorated with pymanopt.function.autograd(manifold).
# This decorator signifies that cost will be optimized on the specified manifold (Stiefel manifold in this case).

@pymanopt.function.autograd(manifold)
def cost(X):
    return -np.trace(X.T @ matrix @ X)

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = jnp.linalg.eig(matrix)


dominant_eigenvector = eigenvectors[:, eigenvalues.real.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)


Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -2.3289403915405273e+00    1.06161457e+00    
   2         -2.4225068092346191e+00    1.50937707e+00    
   3         -2.6795835494995117e+00    5.72138963e-01    
   4         -2.7029390335083008e+00    4.07136132e-01    
   5         -2.7206792831420898e+00    1.13617405e-01    
   6         -2.7219505310058594e+00    6.19872011e-02    
   7         -2.7223291397094727e+00    3.08652046e-02    
   8         -2.7223877906799316e+00    2.38152103e-02    
   9         -2.7224059104919434e+00    2.06052954e-02    
  10         -2.7224502563476562e+00    4.76510308e-03    
  11         -2.7224531173706055e+00    7.93748860e-04    
  12         -2.7224531173706055e+00    7.93744233e-04    
Terminated - min step_size reached after 12 iterations, 0.09 seconds.

Dominant eigenvector: [-0.28785697+0.j -0.62386155+0.j -0.6074242 +0.j -0.3987117 +0.j]
P